create sequence credit_plan_member_id_seq;

create type credit_plan_status as enum ('ACTIVE', 'INACTIVE');

create table credit_plan
(
    member_id       bigint                                                     not null
        constraint fk_credit_plan_member
            references probuilds.member,
    application_id  varchar(255)                                               not null
        primary key
        constraint uq_credit_plan_application_id
            unique,
    duration_months integer,
    total_price     double precision,
    monthly_payment numeric(38, 2),
    start_date      date,
    status          varchar(255) default 'ACTIVE'::fintrust.credit_plan_status not null,
    end_date        date
);

create sequence tool_tool_id_seq
    as integer;

create sequence hire_order_hire_order_id_seq
    as integer;

create sequence sale_order_sale_order_id_seq
    as integer;

create type availability_status as enum ('available', 'unavailable');

create type payment_method_type as enum ('CASH', 'CARD');

create type distribution_type as enum ('PICKUP', 'DELIVERY');

create type sale_status as enum ('PENDING', 'DELIVERED', 'PICKED_UP');

create type hire_status as enum ('PENDING', 'PICKED_UP', 'RETURNED');

create type tool_instance_status as enum ('AVAILABLE', 'HIRED', 'MAINTENANCE', 'RETIRED', 'SOLD');

create table member
(
    member_id      bigint generated by default as identity
        constraint member_pk
            primary key,
    firstname      varchar(255)              not null,
    surname        varchar(255)              not null,
    dob            timestamp(6)              not null,
    email          varchar(255)              not null,
    phone_number   varchar(255),
    created_at     date default CURRENT_DATE not null,
    loyalty_points integer
);

create table tool
(
    tool_id      bigint default nextval('probuilds.tool_tool_id_seq'::regclass) not null
        primary key,
    tool_name    text,
    price        double precision,
    tool_type    text
        constraint tool_tool_type_check
            check (tool_type = ANY (ARRAY ['HIRE'::text, 'SALE'::text])),
    availability probuilds.availability_status
        constraint tool_availability_check
            check (availability = ANY
                   (ARRAY ['available'::probuilds.availability_status, 'unavailable'::probuilds.availability_status]))
);

alter sequence tool_tool_id_seq owned by tool.tool_id;

create table hire_order
(
    order_id           varchar(255)                                          not null
        primary key,
    member_id          bigint
        references member,
    tool_id            bigint
        references tool,
    quantity           integer,
    total_price        double precision,
    payment_method     varchar(255)                                          not null,
    distribution_type  varchar(255)                                          not null,
    order_date         date,
    status             varchar(255) default 'PENDING'::probuilds.hire_status not null,
    condition_at_issue varchar(50),
    condition_notes    varchar(255),
    issue_date         date,
    expected_return    date,
    actual_return      date
);

create table sale_order
(
    order_id          varchar(255)                                                   not null
        primary key,
    member_id         bigint
        references member,
    tool_id           bigint
        references tool,
    quantity          integer,
    total_price       numeric(10, 2),
    payment_method    probuilds.payment_method_type                                  not null,
    distribution_type probuilds.distribution_type                                    not null,
    order_date        date,
    status            probuilds.sale_status default 'PENDING'::probuilds.sale_status not null
);

create table tool_instance
(
    instance_id   bigserial
        primary key,
    tool_id       bigint                                                                             not null
        references tool,
    serial_number varchar(255)
        unique,
    status        probuilds.tool_instance_status default 'AVAILABLE'::probuilds.tool_instance_status not null,
    created_at    date                           default CURRENT_DATE                                not null,
    notes         text
);

create table order_tool_instance
(
    id          bigserial
        primary key,
    order_id    varchar(255) not null,
    instance_id bigint       not null
        references tool_instance,
    order_type  varchar(10)  not null
);

