spring.application.name=camundaWorker
server.port=8082
camunda.client.mode=self-managed
camunda.client.grpc-address=http://127.0.0.1:26500
camunda.client.rest-address=http://127.0.0.1:8080

logging.level.io.camunda.client.impl.CamundaCallCredentials=ERROR


# ProBuilds Database
spring.datasource.url=jdbc:postgresql://localhost:5432/probuilds
spring.datasource.username=ZainabMB
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=probuilds
spring.jpa.show-sql=true

# FinTrust Database
#spring.datasource.fintrust.url=jdbc:postgresql://localhost:5433/fintrust
#spring.datasource.fintrust.username=ZainabMB
#spring.datasource.fintrust.driver-class-name=org.postgresql.Driver
