camunda.client.mode=saas
camunda.client.auth.client-id=bF7K60nfqeI6MKn3zifZvGOWEMDecJEo
camunda.client.auth.client-secret=4vynb-RfaydmGoVJw-cEzz~050x4PJx92~IjI1aP~sa~p6.8EaQe15nyI3YRu-EX
camunda.client.cloud.cluster-id=848240b1-573c-4a07-bd52-723bea5b23b7
camunda.client.cloud.region=lhr-1
logging.level.io.camunda.client.impl.oauth=DEBUG
logging.level.io.camunda.client.impl.http=DEBUG